# Generated by Django 3.2.3 on 2021-06-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readtable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fao',
            name='username',
        ),
        migrations.RemoveField(
            model_name='fao',
            name='year',
        ),
        migrations.RemoveField(
            model_name='mapuretimler',
            name='year',
        ),
        migrations.RemoveField(
            model_name='usda',
            name='year',
        ),
        migrations.AddField(
            model_name='fao',
            name='birim',
            field=models.CharField(blank=True, choices=[('TON', 'TON'), ('ha', 'ha'), ('hg/ha', 'hg/ha')], max_length=256, null=True, verbose_name='Birim'),
        ),
        migrations.AddField(
            model_name='fao',
            name='degisken',
            field=models.CharField(blank=True, choices=[('Ekim alanı', 'Ekim alanı'), ('Verim', 'Verim'), ('Üretim', 'Üretim')], max_length=256, null=True, verbose_name='Değişken'),
        ),
        migrations.AddField(
            model_name='fao',
            name='kaynak',
            field=models.CharField(blank=True, choices=[('FAO', 'FAO')], max_length=256, null=True, verbose_name='Kaynak'),
        ),
        migrations.AddField(
            model_name='fao',
            name='ulke',
            field=models.CharField(blank=True, choices=[('Ermenistan', 'Ermenistan')], max_length=256, null=True, verbose_name='Ülke'),
        ),
        migrations.AddField(
            model_name='fao',
            name='urun',
            field=models.CharField(blank=True, choices=[('Badem', 'Badem'), ('Elma', 'Elma'), ('Kayısı', 'Kayısı')], max_length=256, null=True, verbose_name='Ürün'),
        ),
        migrations.AddField(
            model_name='fao',
            name='yil',
            field=models.IntegerField(blank=True, choices=[(2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007)], null=True, verbose_name='Yıl'),
        ),
        migrations.AddField(
            model_name='mapuretimler',
            name='acilan_kutu',
            field=models.CharField(blank=True, choices=[(None, None)], max_length=256, null=True, verbose_name='Açılan Kutu'),
        ),
        migrations.AddField(
            model_name='mapuretimler',
            name='birim_hasat_alani',
            field=models.CharField(blank=True, choices=[('Dekar', 'Dekar')], max_length=256, null=True, verbose_name='Birim Hasat Alanı'),
        ),
        migrations.AddField(
            model_name='mapuretimler',
            name='birim_uretim',
            field=models.CharField(blank=True, choices=[('Ton', 'Ton')], max_length=256, null=True, verbose_name='Birim Üretim'),
        ),
        migrations.AddField(
            model_name='mapuretimler',
            name='birim_verim',
            field=models.CharField(blank=True, choices=[('Aladağ', 'Aladağ'), ('Ceyhan', 'Ceyhan'), ('Feke', 'Feke'), ('Karaisalı', 'Karaisalı'), ('Karataş', 'Karataş'), ('Seyhan', 'Seyhan'), ('Yüreğir', 'Yüreğir'), ('İmamoğlu', 'İmamoğlu')], max_length=256, null=True, verbose_name='Birim Verim'),
        ),
        migrations.AddField(
            model_name='mapuretimler',
            name='grup_adi',
            field=models.CharField(blank=True, choices=[('Patates-Kuru Baklagiller-Yenilebilir Kök Ve Yumrular', 'Patates-Kuru Baklagiller-Yenilebilir Kök Ve Yumrular'), ('Saman Ve Ot', 'Saman Ve Ot'), ('Tahıllar', 'Tahıllar'), ('Tekstilde Kullanılan Ham Bitkiler', 'Tekstilde Kullanılan Ham Bitkiler'), ('Yağlı Tohumlar', 'Yağlı Tohumlar')], max_length=256, null=True, verbose_name='Grup Adı'),
        ),
        migrations.AddField(
            model_name='mapuretimler',
            name='hane_sayisi',
            field=models.CharField(blank=True, choices=[(None, None)], max_length=256, null=True, verbose_name='Hane Sayısı (Adet)'),
        ),
        migrations.AddField(
            model_name='mapuretimler',
            name='hasat_edilen_alan',
            field=models.CharField(blank=True, choices=[('Patates-Kuru Baklagiller-Yenilebilir Kök Ve Yumrular', 'Patates-Kuru Baklagiller-Yenilebilir Kök Ve Yumrular'), ('Saman Ve Ot', 'Saman Ve Ot'), ('Tahıllar', 'Tahıllar'), ('Tekstilde Kullanılan Ham Bitkiler', 'Tekstilde Kullanılan Ham Bitkiler'), ('Yağlı Tohumlar', 'Yağlı Tohumlar')], max_length=256, null=True, verbose_name='Hasat Edilen Alan'),
        ),
        migrations.AddField(
            model_name='mapuretimler',
            name='il_adi',
            field=models.CharField(blank=True, choices=[('Aladağ', 'Aladağ'), ('Ceyhan', 'Ceyhan'), ('Feke', 'Feke'), ('Karaisalı', 'Karaisalı'), ('Karataş', 'Karataş'), ('Seyhan', 'Seyhan'), ('Yüreğir', 'Yüreğir'), ('İmamoğlu', 'İmamoğlu')], max_length=256, null=True, verbose_name='İl Adı'),
        ),
        migrations.AddField(
            model_name='mapuretimler',
            name='ilce_adi',
            field=models.CharField(blank=True, choices=[('Aladağ', 'Aladağ'), ('Ceyhan', 'Ceyhan'), ('Feke', 'Feke'), ('Karaisalı', 'Karaisalı'), ('Karataş', 'Karataş'), ('Seyhan', 'Seyhan'), ('Yüreğir', 'Yüreğir'), ('İmamoğlu', 'İmamoğlu')], max_length=256, null=True, verbose_name='İlçe Adı'),
        ),
        migrations.AddField(
            model_name='mapuretimler',
            name='kirkilan_hayvan_sayisi_bas',
            field=models.CharField(blank=True, choices=[(None, None)], max_length=256, null=True, verbose_name='Kırkılan Hayvan Sayısı (Baş)'),
        ),
        migrations.AddField(
            model_name='mapuretimler',
            name='koy_sayisi',
            field=models.CharField(blank=True, choices=[(None, None)], max_length=256, null=True, verbose_name='Köy Sayısı (Adet)'),
        ),
        migrations.AddField(
            model_name='mapuretimler',
            name='madde_adi',
            field=models.CharField(blank=True, choices=[('Arpa (Diğer)', 'Arpa (Diğer)'), ('Ayçiçeği (Yağlık)', 'Ayçiçeği (Yağlık)'), ('Ayçiçeği (Çerezlik)', 'Ayçiçeği (Çerezlik)'), ('Buğday (Diğer)', 'Buğday (Diğer)'), ('Fasulye (Kuru)', 'Fasulye (Kuru)'), ('Fiğ (Kuru Ot)', 'Fiğ (Kuru Ot)'), ('Fiğ (Yeşil Ot)', 'Fiğ (Yeşil Ot)'), ('Kolza (Kanola)', 'Kolza (Kanola)'), ('Mercimek (Yeşil)', 'Mercimek (Yeşil)'), ('Mısır (Dane)', 'Mısır (Dane)'), ('Mısır (Silajlık)', 'Mısır (Silajlık)'), ('Nohut', 'Nohut'), ('Pamuk (Kütlü)', 'Pamuk (Kütlü)'), ('Pamuk (Lif)', 'Pamuk (Lif)'), ('Pamuk Tohumu (Çiğit)', 'Pamuk Tohumu (Çiğit)'), ('Patates (Diğer)', 'Patates (Diğer)'), ('Sorgum (Dane)', 'Sorgum (Dane)'), ('Soya', 'Soya'), ('Susam', 'Susam'), ('Yerfıstığı', 'Yerfıstığı'), ('Yonca (Kuru Ot)', 'Yonca (Kuru Ot)'), ('Yonca (Yeşil Ot)', 'Yonca (Yeşil Ot)'), ('Çeltik', 'Çeltik')], max_length=256, null=True, verbose_name='Madde Adı'),
        ),
        migrations.AddField(
            model_name='mapuretimler',
            name='meyve_veren_yasta_agac_sayisi',
            field=models.CharField(blank=True, choices=[(None, None)], max_length=256, null=True, verbose_name='Meyve Veren Yaşta Ağaç Sayısı'),
        ),
        migrations.AddField(
            model_name='mapuretimler',
            name='meyve_vermeyen_yasta_agac_sayisi',
            field=models.CharField(blank=True, choices=[(None, None)], max_length=256, null=True, verbose_name='Meyve Vermeyen Yaşta Ağaç Sayısı'),
        ),
        migrations.AddField(
            model_name='mapuretimler',
            name='sagilan_hayvan_bas',
            field=models.CharField(blank=True, choices=[(None, None)], max_length=256, null=True, verbose_name='Sağılan Hayvan (Baş)'),
        ),
        migrations.AddField(
            model_name='mapuretimler',
            name='yil',
            field=models.CharField(blank=True, choices=[(2009, 2009)], max_length=256, null=True, verbose_name='Yıl'),
        ),
        migrations.AddField(
            model_name='usda',
            name='birim',
            field=models.CharField(blank=True, choices=[('TON', 'TON')], max_length=256, null=True, verbose_name='Birim'),
        ),
        migrations.AddField(
            model_name='usda',
            name='degisken',
            field=models.CharField(blank=True, choices=[('Başlangıç Stok', 'Başlangıç Stok'), ('Domestic Consumption', 'Domestic Consumption'), ('Toplam Dağılım', 'Toplam Dağılım'), ('Toplam Tedarik', 'Toplam Tedarik'), ('Yıl Sonu Stoğu', 'Yıl Sonu Stoğu'), ('Üretim', 'Üretim'), ('İhracat', 'İhracat'), ('İthalat', 'İthalat')], max_length=256, null=True, verbose_name='Değişken'),
        ),
        migrations.AddField(
            model_name='usda',
            name='kalem',
            field=models.CharField(blank=True, choices=[('Antep Fıstığı içi', 'Antep Fıstığı içi')], max_length=256, null=True, verbose_name='Kalem'),
        ),
        migrations.AddField(
            model_name='usda',
            name='kaynak',
            field=models.CharField(blank=True, choices=[('USDA', 'USDA')], max_length=256, null=True, verbose_name='Kaynak'),
        ),
        migrations.AddField(
            model_name='usda',
            name='ulke',
            field=models.CharField(blank=True, choices=[('ABD', 'ABD')], max_length=256, null=True, verbose_name='Ülke'),
        ),
        migrations.AddField(
            model_name='usda',
            name='yil',
            field=models.IntegerField(blank=True, choices=[(2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007)], null=True, verbose_name='Yıl'),
        ),
    ]
