columns_dict = {
    'KALEM': 'KALEM',
    'URUN': 'ÜRÜN ADI',
    'YIL': 'YIL',
    'AY': 'AY',
    'COUNTRY_TR': 'ÜLKE',
    'Market_Year': 'YIL',
    'Year': 'YIL',
    'KALEM_ADI': 'KALEM',
    'ISTPOZ_ADI': 'ISTPOZ ADI',
    'ULKE_ADI': 'ÜLKE ADI',
    'ULKE': 'ÜLKE ADI',
    'OLCU_ADI': 'ÖLÇÜ ADI',
    'SUM(ITHALAT_MIKTAR1)': 'İTHALAT MİKTARI 1',
    'SUM(ITHALAT_MIKTAR2)': 'İTHALAT MİKTARI 2',
    'SUM(ITHALAT_DOLAR)': 'İTHALAT DOLAR',
    'SUM(IHRACAT_MIKTAR1)': 'İHRACAT MİKTARI 1',
    'SUM(IHRACAT_MIKTAR2)': 'İHRACAT MİKTARI 2',
    'SUM(IHRACAT_DOLAR)': 'İHRACAT DOLAR',
    'ISTPOZ': 'ISTPOZ',
    'GTIP6': 'GTIP6',
    'ALT KALEM': 'ALT KALEM',
    'ACIKLAMA': 'AÇIKLAMA',
    'MIKTAR': 'MİKTAR',
    'BIRIM': 'BİRİM',
    'DEGISKEN': 'DEĞİŞKEN',
    'KAYNAK': 'KAYNAK',
    'DEGER': 'DEĞER',
    'SUM(Value)': 'DEĞER',
    'HEDEF_ULKE': 'HEDEF ÜLKE',
    'TICARET_YONU': 'TİCARET YÖNÜ',
    'DEGER_USD': 'DEĞER (USD)',
    'FIYAT_TUFE': 'FİYAT TÜFE',
    'FIYAT_UFE': 'FİYAT ÜFE'
}

view_to_obj ={
    'FaoView':'fao',
    'UsdaView':'usda',
    'MapUretimlerView':'mapuretimler',
    'TufeView':'tufe',
    'UfeView':'ufe',
    'TuikView':'tuik',
    'TuikexternalView':'tuikexternal',
    'TuikdirexternalView':'tuikdirexternal',
    'TuikotsexternalView':'tuikotsexternal',
    'TuikotsdirexternalView':'tuikotsdirexternal',
    'WorldagricultureView':'worldagriculture',
    'ProductpriceView':'productprice',

    'faoList':'fao',
    'usdaList':'usda',
    'ufeList':'ufe',
    'tufeList':'tufe',
    'mapuretimlerList':'mapuretimler',
    'tuikList':'tuik',
    'tuikdirexternalList':'tuikdirexternal',
    'tuikexternalList':'tuikexternal',
    'tuikotsdirexternalList':'tuikotsdirexternal',
    'tuikotsexternalList':'tuikotsexternal',
    'worldagricultureList':'worldagriculture',
    'productpriceList':'productprice'
    
    }